In [1]:
# import the necessary packages
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import os

In [2]:
# load our serialized face detector model from disk
prototxtPath=os.path.sep.join([r'D:\Face mask detector\dataset\face_detector','deploy.prototxt'])
weightsPath=os.path.sep.join([r'D:\Face mask detector\dataset\face_detector','res10_300x300_ssd_iter_140000.caffemodel'])


In [3]:
# prototxtPath

In [4]:
# weightsPath

In [5]:
net=cv2.dnn.readNet(prototxtPath,weightsPath)

In [6]:
# net

In [7]:
model=load_model(r'D:\Face mask detector\dataset\face_mobilenet_v2.model')

In [8]:
image=cv2.imread(r'D:\Face mask detector\dataset\example\example_05.png')

In [9]:
image

array([[[ 98, 127, 163],
        [ 98, 127, 163],
        [ 98, 127, 163],
        ...,
        [143, 166, 194],
        [143, 166, 194],
        [143, 166, 194]],

       [[ 92, 117, 157],
        [ 92, 117, 157],
        [ 98, 127, 163],
        ...,
        [143, 166, 194],
        [143, 166, 194],
        [143, 166, 194]],

       [[ 98, 127, 163],
        [ 92, 117, 157],
        [ 98, 127, 163],
        ...,
        [143, 166, 194],
        [143, 166, 194],
        [143, 166, 194]],

       ...,

       [[128, 155, 190],
        [121, 148, 183],
        [ 98, 127, 163],
        ...,
        [194, 175, 158],
        [194, 175, 158],
        [190, 172, 156]],

       [[121, 148, 183],
        [121, 148, 183],
        [128, 155, 190],
        ...,
        [194, 175, 158],
        [194, 175, 158],
        [190, 172, 156]],

       [[ 47,  76, 123],
        [ 55,  90, 137],
        [ 84, 110, 151],
        ...,
        [190, 172, 156],
        [187, 169, 154],
        [190, 172, 156]]

In [10]:
image.shape

(600, 600, 3)

In [11]:
(h,w)=image.shape[:2]

In [12]:
(h,w)

(600, 600)

In [13]:
# construct a blob from the image
blob=cv2.dnn.blobFromImage(image,1.0,(300,300),(104.0,177.0,123.0))

In [14]:
blob

array([[[[  -9.,   -7.,   -9., ...,   39.,   39.,   39.],
         [  -9.,   -6.,   -7., ...,   40.,   39.,   39.],
         [  -6.,   -7.,   -9., ...,   38.,   39.,   39.],
         ...,
         [ -42.,  -56.,   18., ...,   81.,   82.,   85.],
         [   8.,  -28.,   20., ...,   85.,   86.,   86.],
         [ -18.,    7.,   16., ...,   89.,   87.,   86.]],

        [[ -55.,  -52.,  -55., ...,  -11.,  -11.,  -11.],
         [ -55.,  -50.,  -52., ...,  -10.,  -11.,  -11.],
         [ -50.,  -52.,  -55., ...,  -12.,  -11.,  -11.],
         ...,
         [ -98., -113.,  -28., ...,  -10.,   -9.,   -6.],
         [ -39.,  -76.,  -26., ...,   -6.,   -6.,   -5.],
         [ -61.,  -39.,  -30., ...,   -3.,   -4.,   -5.]],

        [[  37.,   39.,   37., ...,   71.,   71.,   71.],
         [  37.,   40.,   39., ...,   71.,   71.,   71.],
         [  40.,   39.,   37., ...,   71.,   67.,   71.],
         ...,
         [ -18.,  -40.,   61., ...,   29.,   30.,   32.],
         [  52.,   11.,   

In [15]:
blob.shape

(1, 3, 300, 300)

In [16]:
# pass the blob through the network and obtain the face detection
net.setInput(blob)
detections=net.forward()

In [17]:
detections

array([[[[ 0.00000000e+00,  1.00000000e+00,  9.89378273e-01,
           5.76706469e-01,  2.20713884e-01,  7.32671440e-01,
           3.63932043e-01],
         [ 0.00000000e+00,  1.00000000e+00,  9.84387636e-01,
           9.22202244e-02,  3.33555907e-01,  2.57166564e-01,
           4.88085836e-01],
         [ 0.00000000e+00,  1.00000000e+00,  9.75802600e-01,
           8.15442145e-01,  2.75532961e-01,  9.92336690e-01,
           4.46491063e-01],
         [ 0.00000000e+00,  1.00000000e+00,  9.47812617e-01,
           3.32406849e-01,  3.89148355e-01,  4.83362347e-01,
           5.44419885e-01],
         [ 0.00000000e+00,  1.00000000e+00,  1.26217321e-01,
           2.08635032e-02,  1.25927866e-01,  9.85216618e-01,
           8.70008409e-01],
         [ 0.00000000e+00,  1.00000000e+00,  1.23381503e-01,
           4.15460300e+00,  4.00493193e+00,  4.84318829e+00,
           4.97861433e+00],
         [ 0.00000000e+00,  1.00000000e+00,  1.22972429e-01,
           4.01592731e+00,  1.29618913e

In [ ]:
#loop over the detections
for i in range(0,detections.shape[2]):
    confidence=detections[0,0,i,2]
    
    
    if confidence>0.5:
        #we need the X,Y coordinates
        box=detections[0,0,i,3:7]*np.array([w,h,w,h])
        (startX,startY,endX,endY)=box.astype('int')
        
        #ensure the bounding boxes fall within the dimensions of the frame
        (startX,startY)=(max(0,startX),max(0,startY))
        (endX,endY)=(min(w-1,endX), min(h-1,endY))
        
        #extract the face ROI, convert it from BGR to RGB channel, resize it to 224,224 and preprocess it
        face=image[startY:endY, startX:endX]
        face=cv2.cvtColor(face,cv2.COLOR_BGR2RGB)
        face=cv2.resize(face,(224,224))
        face=img_to_array(face)
        face=preprocess_input(face)
        face=np.expand_dims(face,axis=0)
        
        # pass the face through the model to determine if the face has a mask or not
        (mask,withoutMask)=model.predict(face)[0]
        
        #determine the class label and color we will use to draw the bounding box and text
        label='Mask' if mask>withoutMask else 'No Mask'
        color=(0,255,0) if label=='Mask' else (0,0,255)
        
        #include the probability in the label
        label="{}: {:.2f}%".format(label,max(mask,withoutMask)*100)
        
        #display the label and bounding boxes
        cv2.putText(image,label,(startX,startY-10),cv2.FONT_HERSHEY_SIMPLEX,0.45,color,2)
        cv2.rectangle(image,(startX,startY),(endX,endY),color,2)
        
        
        
cv2.imshow("OutPut",image)
cv2.waitKey(0)
cv2.destroyAllWindows()
        